version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        update-types: [minor, patch]
        exclude-patterns:
          - class-validator
          - esbuild
  - package-ecosystem: pip
    directory: /services/mlx-embedding
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /deploy/mac
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      codeql:
        patterns:
          - github/codeql-action/*
